### ISSUE TITLE
Мех РИПЛИ сломан.

### ISSUE THREAD

**Issue by Ro2tCrab** [iWuna/Fallout-13-RoseEdition#132]
Issue reported from  Round ID: 590 ([RU] Fallout 13 - CBET ATOMA [REDUX])

Reporting client version: 513

Фонарик меха РИПЛИ сломан!
 - Не освещает дальше своего тайтла.
Авто-использование дрели при ходьбе не работает.
- Если шагнуть на тайтл с камнем и у тебя включен модуль дрели, то автоматически мех начнёт копать камни.

**Comment by Reishi42** [comment]
Выпилим рипли. Можно закрывать иссуй
